name_list = {...
%    'corral', ...
%    'cherries', ...
%    'pointilliste', ...
	'town', ...
    'mures',...
    'peoples',...
    'radishes',...
    'olives',...
    'pasta',...
    'frenchfries',...
    'framboise', ...
    'tomatoes',...
    'dunes', ...
    'reptil_skin', ...
};

for iname = 1:length(name_list)
    name = name_list{iname};
    disp(['--> Inpainting ' name '.']);
    test_nl_inpainting;
end